version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: coding_share_front
    networks:
      - coding_share_net
    secrets:
      - server.crt
      - server.key

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: coding_share_server
    networks:
      - coding_share_net
    env_file:
      - .env
    secrets:
      - server.crt
      - server.key
    depends_on:
      - db
  db:
    image: mariadb:10.5.8
    container_name: coding_share_db_server
    networks:
      - coding_share_net
    command: mysqld --character-set-server=utf8mb4  --collation-server=utf8mb4_general_ci
    env_file:
      - .env

  proxy_server:
    build:
      context: ./proxy_server
      dockerfile: Dockerfile
    container_name: coding_share_proxy_server
    env_file:
      - .env
    networks:
      - coding_share_net
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - server
    secrets:
      - server.crt
      - server.key

networks:
  coding_share_net:
    driver: bridge

secrets:
  server.crt:
    file: ${CERTIFICATE_FILE_PATH}
  server.key:
    file: ${KEY_FILE_PATH}
