version: '3.8'
services:
  front:
    image: node:14.15.5
    container_name: front_dev_container
    command: npm run serve
    restart: always
    ports:
      - 10081:8080
    working_dir: /app
    volumes:
      - ./front:/app
